### ISSUE TITLE
安卓部署语义分割推理无结果

### ISSUE THREAD

**Issue by fanweiya** [PaddlePaddle/Paddle-Lite-Demo#145]
使用自己训练FastSCNN的模型，经过opt 2.9.1转换之后，替换human_segmentation_demo里的nb模型文件，推理没有任何分割结果输出，但是测试转换前inference_model是可以正常分割的。
下面是我模型的yml文件
```
Model: FastSCNN
Transforms:
- ResizeByLong:
    long_size: 512
- Padding:
    im_padding_value:
    - 127.5
    - 127.5
    - 127.5
    label_padding_value: 255
    target_size: 512
- Normalize:
    max_val:
    - 255.0
    - 255.0
    - 255.0
    mean:
    - 0.5
    - 0.5
    - 0.5
    min_val:
    - 0
    - 0
    - 0
    std:
    - 0.5
    - 0.5
    - 0.5
TransformsMode: BGR
_Attributes:
  eval_metrics:
    miou: 0.9247056221142143
  fixed_input_shape: null
  labels:
  - _background_
  - organoid
  model_type: segmenter
  num_classes: 2
_ModelInputsOutputs:
  test_inputs:
  - - image
    - image
  test_outputs:
  - - pred
    - unsqueeze2_0.tmp_0
  - - logit
    - softmax_0.tmp_0
_init_params:
  class_weight: null
  ignore_index: 255
  input_channel: 3
  multi_loss_weight:
  - 1.0
  num_classes: 2
  use_bce_loss: false
  use_dice_loss: false
completed_epochs: 0
status: Quant
version: 1.2.8
```
