### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by premeditate** [PaddlePaddle/Paddle-Lite-Demo#260]
我下载运行官方picodet_detection_demo程序可以运行

将模型文件换成自己的模型时程序运行闪退,在logcat中产生如下错误日志:
```
2022-05-10 10:31:24.711 617-1851/com.baidu.paddle.lite.demo.ssd_detection A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x72dd200000 in tid 1851 (GLThread 2144), pid 617 (o.ssd_detection)
```
还有一些警告日志:
```
W/linker: Warning: "/data/app/com.baidu.paddle.lite.demo.ssd_detection-X59q7PzHvLycKCBryFI04Q==/lib/arm64/libpaddle_light_api_shared.so" unused DT entry: DT_RPATH (type 0xf arg 0x3026) (ignoring)
```
```
warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
      version of opt:v2.10-rc
      version of current Paddle-Lite:d394c9e
```

我的模型是通过paddledetection训练picodet目标检测模型,配置文件为picodet_s_320_voc.yml，数据集为自定义的，训练了170个epoch，并输出best_model.然后通过一下命令输出inference模型:
```
python tools/export_model.py -c configs/picodet/picodet_s_320_voc_j31.yml --output_dir=output_j31 -o weights=output/best/best_model.pdparams
```
inference模型的infer_cfg.yml文件内容如下:
```
mode: fluid
draw_threshold: 0.5
metric: VOC
use_dynamic_shape: false
arch: PicoDet
min_subgraph_size: 3
Preprocess:
- interp: 2
  keep_ratio: false
  target_size:
  - 320
  - 320
  type: Resize
- is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeImage
- type: Permute
- stride: 32
  type: PadStride
label_list:
- fighter
NMS:
  keep_top_k: 100
  name: MultiClassNMS
  nms_threshold: 0.5
  nms_top_k: 1000
  score_threshold: 0.3
fpn_stride:
- 8
- 16
- 32
- 64
```

然后通过opt工具转换nb模型,转换代码如下:
```
# 引用Paddlelite预测库
from paddlelite.lite import *

# 1. 创建opt实例
opt=Opt()
# 2. 指定输入模型地址
opt.set_model_dir('model/picodetj31')
# 3. 指定转化类型： arm、x86、opencl、npu
opt.set_valid_places("arm")
# 4. 指定模型转化类型： naive_buffer、protobuf
opt.set_model_type("naive_buffer")
# 4. 输出模型地址
opt.set_optimize_out("picodet-opt")
# 5. 执行模型优化
opt.run()
```

得到nb模型的输入如下图:
![微信图片_20220510105106](https://user-images.githubusercontent.com/85290082/167533345-26e44a8b-035f-4470-b10c-4a7d1775570b.png)

因为我的模型文件输出只有一个,因此将/src/main/cpp/Pipeline.cc文件中的输入参数位置进行了修改:
```
void Detector::Preprocess(const cv::Mat &rgbaImage) {
  // Feed the input tensor with the data of the preprocessed image
//  auto input_tensor_scale = predictor_->GetInput(1);
//  input_tensor_scale->Resize({1, 2});
//  auto *scale_data = input_tensor_scale->mutable_data<float>();
//  scale_data[0] =
//      static_cast<float>(inputHeight_) / static_cast<float>(rgbaImage.rows);
//  scale_data[1] =
//      static_cast<float>(inputWidth_) / static_cast<float>(rgbaImage.cols);

  auto inputTensor = predictor_->GetInput(0);
  std::vector<int64_t> inputShape = {1, 3, inputHeight_, inputWidth_};
  inputTensor->Resize(inputShape);
  auto inputData = inputTensor->mutable_data<float>();
  cv::Mat resizedRGBAImage;
  cv::resize(rgbaImage, resizedRGBAImage,
             cv::Size(inputShape[3], inputShape[2]));
  cv::Mat resizedRGBImage;
  cv::cvtColor(resizedRGBAImage, resizedRGBImage, cv::COLOR_BGRA2RGB);
  resizedRGBImage.convertTo(resizedRGBImage, CV_32FC3, 1.0 / 255.0f);
  NHWC3ToNC3HW(reinterpret_cast<const float *>(resizedRGBImage.data), inputData,
               inputMean_.data(), inputStd_.data(), inputShape[3],
               inputShape[2]);
}
```

请问是哪里的操作出问题了呢?
